<?php
/**
 * @file
 * ctt_structure.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function ctt_structure_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: main-menu_1801-1860:taxonomy/term/18.
  $menu_links['main-menu_1801-1860:taxonomy/term/18'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/18',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1801-1860',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1801-1860:taxonomy/term/18',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_19th-century:taxonomy/term/7',
  );
  // Exported menu link: main-menu_1861-1890:taxonomy/term/23.
  $menu_links['main-menu_1861-1890:taxonomy/term/23'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/23',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1861-1890',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1861-1890:taxonomy/term/23',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_19th-century:taxonomy/term/7',
  );
  // Exported menu link: main-menu_1891-1900:taxonomy/term/19.
  $menu_links['main-menu_1891-1900:taxonomy/term/19'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/19',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1891-1900',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1891-1900:taxonomy/term/19',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_19th-century:taxonomy/term/7',
  );
  // Exported menu link: main-menu_1901-1950:taxonomy/term/14.
  $menu_links['main-menu_1901-1950:taxonomy/term/14'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/14',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1901-1950',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1901-1950:taxonomy/term/14',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_20th-century:taxonomy/term/8',
  );
  // Exported menu link: main-menu_1951-1960:taxonomy/term/15.
  $menu_links['main-menu_1951-1960:taxonomy/term/15'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/15',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1951-1960',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1951-1960:taxonomy/term/15',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_20th-century:taxonomy/term/8',
  );
  // Exported menu link: main-menu_1961-1970:taxonomy/term/20.
  $menu_links['main-menu_1961-1970:taxonomy/term/20'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/20',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1961-1970',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1961-1970:taxonomy/term/20',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_20th-century:taxonomy/term/8',
  );
  // Exported menu link: main-menu_1971-1980:taxonomy/term/21.
  $menu_links['main-menu_1971-1980:taxonomy/term/21'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/21',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1971-1980',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1971-1980:taxonomy/term/21',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_20th-century:taxonomy/term/8',
  );
  // Exported menu link: main-menu_1981-1990:taxonomy/term/22.
  $menu_links['main-menu_1981-1990:taxonomy/term/22'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/22',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1981-1990',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1981-1990:taxonomy/term/22',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_20th-century:taxonomy/term/8',
  );
  // Exported menu link: main-menu_1991-2000:taxonomy/term/16.
  $menu_links['main-menu_1991-2000:taxonomy/term/16'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/16',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1991-2000',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_1991-2000:taxonomy/term/16',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_20th-century:taxonomy/term/8',
  );
  // Exported menu link: main-menu_19th-century:taxonomy/term/7.
  $menu_links['main-menu_19th-century:taxonomy/term/7'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/7',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '19th Century',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_19th-century:taxonomy/term/7',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_anthologies--histories:taxonomy/term/29',
  );
  // Exported menu link: main-menu_2001-:taxonomy/term/17.
  $menu_links['main-menu_2001-:taxonomy/term/17'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/17',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '2001-',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_2001-:taxonomy/term/17',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_21st-century:taxonomy/term/9',
  );
  // Exported menu link: main-menu_20th-century:taxonomy/term/8.
  $menu_links['main-menu_20th-century:taxonomy/term/8'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/8',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '20th Century',
    'options' => array(
      'attributes' => array(
        'title' => '20th Century',
      ),
      'identifier' => 'main-menu_20th-century:taxonomy/term/8',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_anthologies--histories:taxonomy/term/29',
  );
  // Exported menu link: main-menu_21st-century:taxonomy/term/9.
  $menu_links['main-menu_21st-century:taxonomy/term/9'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/9',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '21st Century',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_21st-century:taxonomy/term/9',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_anthologies--histories:taxonomy/term/29',
  );
  // Exported menu link: main-menu_a-college-book-of-american-literature-vol-1-1939:node/139.
  $menu_links['main-menu_a-college-book-of-american-literature-vol-1-1939:node/139'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/139',
    'router_path' => 'node/%',
    'link_title' => 'A College Book of American Literature, Vol. 1 (1939)',
    'options' => array(
      'identifier' => 'main-menu_a-college-book-of-american-literature-vol-1-1939:node/139',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_a-college-book-of-american-literature-vol-2-1940:node/140.
  $menu_links['main-menu_a-college-book-of-american-literature-vol-2-1940:node/140'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/140',
    'router_path' => 'node/%',
    'link_title' => 'A College Book of American Literature, Vol. 2 (1940)',
    'options' => array(
      'identifier' => 'main-menu_a-college-book-of-american-literature-vol-2-1940:node/140',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_a-history-of-american-literature-1607-1765-vol-i-1878:node/118.
  $menu_links['main-menu_a-history-of-american-literature-1607-1765-vol-i-1878:node/118'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/118',
    'router_path' => 'node/%',
    'link_title' => 'A History of American Literature, 1607-1765, Vol. I (1878)',
    'options' => array(
      'identifier' => 'main-menu_a-history-of-american-literature-1607-1765-vol-i-1878:node/118',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1861-1890:taxonomy/term/23',
  );
  // Exported menu link: main-menu_a-history-of-american-literature-1607-1765-vol-ii-1878:node/119.
  $menu_links['main-menu_a-history-of-american-literature-1607-1765-vol-ii-1878:node/119'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/119',
    'router_path' => 'node/%',
    'link_title' => 'A History of American Literature, 1607-1765, Vol. II (1878)',
    'options' => array(
      'identifier' => 'main-menu_a-history-of-american-literature-1607-1765-vol-ii-1878:node/119',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1861-1890:taxonomy/term/23',
  );
  // Exported menu link: main-menu_a-history-of-american-literature-1896:node/132.
  $menu_links['main-menu_a-history-of-american-literature-1896:node/132'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/132',
    'router_path' => 'node/%',
    'link_title' => 'A History of American Literature (1896)',
    'options' => array(
      'identifier' => 'main-menu_a-history-of-american-literature-1896:node/132',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -36,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-i-1887-1892:node/121.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-i-1887-1892:node/121'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/121',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. I (1887, 1892)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-i-1887-1892:node/121',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1861-1890:taxonomy/term/23',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-ii-1891:node/122.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-ii-1891:node/122'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/122',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. II (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-ii-1891:node/122',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-iii-1891:node/123.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-iii-1891:node/123'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/123',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. III (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-iii-1891:node/123',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-iv-1891:node/124.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-iv-1891:node/124'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/124',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. IV (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-iv-1891:node/124',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-ix-1891:node/129.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-ix-1891:node/129'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/129',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. IX (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-ix-1891:node/129',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-v-1891:node/125.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-v-1891:node/125'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/125',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. V (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-v-1891:node/125',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-vi-1891:node/126.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-vi-1891:node/126'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/126',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. VI (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-vi-1891:node/126',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-vii-1891:node/127.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-vii-1891:node/127'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/127',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. VII (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-vii-1891:node/127',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-viii-1891:node/128.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-viii-1891:node/128'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/128',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. VIII (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-viii-1891:node/128',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-x-1891:node/130.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-x-1891:node/130'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/130',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. X (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-x-1891:node/130',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-xi-1891:node/131.
  $menu_links['main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-xi-1891:node/131'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/131',
    'router_path' => 'node/%',
    'link_title' => 'A Library of American Literature from the Earliest Settlement to the Present Time, Vol. XI (1891)',
    'options' => array(
      'identifier' => 'main-menu_a-library-of-american-literature-from-the-earliest-settlement-to-the-present-time-vol-xi-1891:node/131',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1891-1900:taxonomy/term/19',
  );
  // Exported menu link: main-menu_a-treasury-of-american-literature-vol-1-1955:node/160.
  $menu_links['main-menu_a-treasury-of-american-literature-vol-1-1955:node/160'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/160',
    'router_path' => 'node/%',
    'link_title' => 'A Treasury of American Literature, Vol. 1 (1955)',
    'options' => array(
      'identifier' => 'main-menu_a-treasury-of-american-literature-vol-1-1955:node/160',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_a-treasury-of-american-literature-vol-2-1955:node/161.
  $menu_links['main-menu_a-treasury-of-american-literature-vol-2-1955:node/161'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/161',
    'router_path' => 'node/%',
    'link_title' => 'A Treasury of American Literature, Vol. 2 (1955)',
    'options' => array(
      'identifier' => 'main-menu_a-treasury-of-american-literature-vol-2-1955:node/161',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_about:node/261.
  $menu_links['main-menu_about:node/261'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/261',
    'router_path' => 'node/%',
    'link_title' => 'About',
    'options' => array(
      'attributes' => array(),
      'identifier' => 'main-menu_about:node/261',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -48,
    'customized' => 1,
  );
  // Exported menu link: main-menu_all:all.
  $menu_links['main-menu_all:all'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'all',
    'router_path' => 'all',
    'link_title' => 'All',
    'options' => array(
      'identifier' => 'main-menu_all:all',
    ),
    'module' => 'system',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
  );
  // Exported menu link: main-menu_america-in-literature-vol-1-1978:node/182.
  $menu_links['main-menu_america-in-literature-vol-1-1978:node/182'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/182',
    'router_path' => 'node/%',
    'link_title' => 'America in Literature, Vol. 1 (1978)',
    'options' => array(
      'identifier' => 'main-menu_america-in-literature-vol-1-1978:node/182',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_america-in-literature-vol-2-1978:node/183.
  $menu_links['main-menu_america-in-literature-vol-2-1978:node/183'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/183',
    'router_path' => 'node/%',
    'link_title' => 'America in Literature, Vol. 2 (1978)',
    'options' => array(
      'identifier' => 'main-menu_america-in-literature-vol-2-1978:node/183',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_american-heritage-vol-1-1955:node/151.
  $menu_links['main-menu_american-heritage-vol-1-1955:node/151'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/151',
    'router_path' => 'node/%',
    'link_title' => 'American Heritage, Vol. 1 (1955)',
    'options' => array(
      'identifier' => 'main-menu_american-heritage-vol-1-1955:node/151',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_american-heritage-vol-2-1955:node/152.
  $menu_links['main-menu_american-heritage-vol-2-1955:node/152'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/152',
    'router_path' => 'node/%',
    'link_title' => 'American Heritage, Vol. 2 (1955)',
    'options' => array(
      'identifier' => 'main-menu_american-heritage-vol-2-1955:node/152',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_american-life-in-literature-vol-1-1949-revision:node/144.
  $menu_links['main-menu_american-life-in-literature-vol-1-1949-revision:node/144'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/144',
    'router_path' => 'node/%',
    'link_title' => 'American Life in Literature, Vol. 1 (1949 Revision)',
    'options' => array(
      'identifier' => 'main-menu_american-life-in-literature-vol-1-1949-revision:node/144',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_american-literary-scholarship-an-annual-1963:node/1690.
  $menu_links['main-menu_american-literary-scholarship-an-annual-1963:node/1690'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1690',
    'router_path' => 'node/%',
    'link_title' => 'American Literary Scholarship: An Annual 1963',
    'options' => array(
      'identifier' => 'main-menu_american-literary-scholarship-an-annual-1963:node/1690',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_american-literary-scholarship:taxonomy/term/27',
  );
  // Exported menu link: main-menu_american-literary-scholarship-an-annual-1964:node/1695.
  $menu_links['main-menu_american-literary-scholarship-an-annual-1964:node/1695'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1695',
    'router_path' => 'node/%',
    'link_title' => 'American Literary Scholarship: An Annual 1964',
    'options' => array(
      'identifier' => 'main-menu_american-literary-scholarship-an-annual-1964:node/1695',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_american-literary-scholarship:taxonomy/term/27',
  );
  // Exported menu link: main-menu_american-literary-scholarship-an-annual-1965:node/1696.
  $menu_links['main-menu_american-literary-scholarship-an-annual-1965:node/1696'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1696',
    'router_path' => 'node/%',
    'link_title' => 'American Literary Scholarship: An Annual 1965',
    'options' => array(
      'identifier' => 'main-menu_american-literary-scholarship-an-annual-1965:node/1696',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_american-literary-scholarship:taxonomy/term/27',
  );
  // Exported menu link: main-menu_american-literary-scholarship-an-annual-1966:node/1765.
  $menu_links['main-menu_american-literary-scholarship-an-annual-1966:node/1765'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1765',
    'router_path' => 'node/%',
    'link_title' => 'American Literary Scholarship: An Annual 1966',
    'options' => array(
      'identifier' => 'main-menu_american-literary-scholarship-an-annual-1966:node/1765',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_american-literary-scholarship:taxonomy/term/27',
  );
  // Exported menu link: main-menu_american-literary-scholarship:taxonomy/term/27.
  $menu_links['main-menu_american-literary-scholarship:taxonomy/term/27'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/27',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'American Literary Scholarship',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_american-literary-scholarship:taxonomy/term/27',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_other-resources:taxonomy/term/25',
  );
  // Exported menu link: main-menu_american-literature--a-prentice-hall-anthology-vol-1-1991:node/191.
  $menu_links['main-menu_american-literature--a-prentice-hall-anthology-vol-1-1991:node/191'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/191',
    'router_path' => 'node/%',
    'link_title' => 'American Literature:  A Prentice Hall Anthology, Vol. 1 (1991)',
    'options' => array(
      'identifier' => 'main-menu_american-literature--a-prentice-hall-anthology-vol-1-1991:node/191',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_american-literature--a-prentice-hall-anthology-vol2-1991:node/192.
  $menu_links['main-menu_american-literature--a-prentice-hall-anthology-vol2-1991:node/192'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/192',
    'router_path' => 'node/%',
    'link_title' => 'American Literature:  A Prentice Hall Anthology, Vol.2 (1991)',
    'options' => array(
      'identifier' => 'main-menu_american-literature--a-prentice-hall-anthology-vol2-1991:node/192',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_american-literature--the-state-of-the-art:node/1703.
  $menu_links['main-menu_american-literature--the-state-of-the-art:node/1703'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1703',
    'router_path' => 'node/%',
    'link_title' => 'American Literature:  The State of the Art',
    'options' => array(
      'identifier' => 'main-menu_american-literature--the-state-of-the-art:node/1703',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_american-literature-extra-essays:taxonomy/term/28',
  );
  // Exported menu link: main-menu_american-literature-1607-1765-1886-1888:node/120.
  $menu_links['main-menu_american-literature-1607-1765-1886-1888:node/120'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/120',
    'router_path' => 'node/%',
    'link_title' => 'American Literature, 1607-1765 (1886, 1888)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-1607-1765-1886-1888:node/120',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1861-1890:taxonomy/term/23',
  );
  // Exported menu link: main-menu_american-literature-1983:node/136.
  $menu_links['main-menu_american-literature-1983:node/136'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/136',
    'router_path' => 'node/%',
    'link_title' => 'American Literature (1983)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-1983:node/136',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1981-1990:taxonomy/term/22',
  );
  // Exported menu link: main-menu_american-literature-extra-essays:taxonomy/term/28.
  $menu_links['main-menu_american-literature-extra-essays:taxonomy/term/28'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/28',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'American Literature Extra Essays',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_american-literature-extra-essays:taxonomy/term/28',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_other-resources:taxonomy/term/25',
  );
  // Exported menu link: main-menu_american-literature-the-makers-and-the-making-vol-1-1973:node/177.
  $menu_links['main-menu_american-literature-the-makers-and-the-making-vol-1-1973:node/177'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/177',
    'router_path' => 'node/%',
    'link_title' => 'American Literature: The Makers and the Making, Vol. 1 (1973)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-the-makers-and-the-making-vol-1-1973:node/177',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_american-literature-the-makers-and-the-making-vol-2-1973:node/178.
  $menu_links['main-menu_american-literature-the-makers-and-the-making-vol-2-1973:node/178'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/178',
    'router_path' => 'node/%',
    'link_title' => 'American Literature: The Makers and the Making, Vol. 2 (1973)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-the-makers-and-the-making-vol-2-1973:node/178',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_american-literature-tradition--innovation-vol-1-1969:node/169.
  $menu_links['main-menu_american-literature-tradition--innovation-vol-1-1969:node/169'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/169',
    'router_path' => 'node/%',
    'link_title' => 'American Literature: Tradition & Innovation, Vol. 1 (1969)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-tradition--innovation-vol-1-1969:node/169',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_american-literature-tradition--innovation-vol-2-1969:node/170.
  $menu_links['main-menu_american-literature-tradition--innovation-vol-2-1969:node/170'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/170',
    'router_path' => 'node/%',
    'link_title' => 'American Literature: Tradition & Innovation, Vol. 2 (1969)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-tradition--innovation-vol-2-1969:node/170',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_american-literature-tradition--innovation-vol-3-1969:node/171.
  $menu_links['main-menu_american-literature-tradition--innovation-vol-3-1969:node/171'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/171',
    'router_path' => 'node/%',
    'link_title' => 'American Literature: Tradition & Innovation, Vol. 3 (1969)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-tradition--innovation-vol-3-1969:node/171',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_american-literature-vol-1-1970:node/172.
  $menu_links['main-menu_american-literature-vol-1-1970:node/172'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/172',
    'router_path' => 'node/%',
    'link_title' => 'American Literature, Vol. 1 (1970)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-vol-1-1970:node/172',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_american-literature-vol-2-1970:node/173.
  $menu_links['main-menu_american-literature-vol-2-1970:node/173'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/173',
    'router_path' => 'node/%',
    'link_title' => 'American Literature, Vol. 2 (1970)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-vol-2-1970:node/173',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_american-literature-vol-i-2004:node/222.
  $menu_links['main-menu_american-literature-vol-i-2004:node/222'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/222',
    'router_path' => 'node/%',
    'link_title' => 'American Literature, Vol. I (2004)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-vol-i-2004:node/222',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_american-literature-vol-ii-2004:node/223.
  $menu_links['main-menu_american-literature-vol-ii-2004:node/223'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/223',
    'router_path' => 'node/%',
    'link_title' => 'American Literature, Vol. II (2004)',
    'options' => array(
      'identifier' => 'main-menu_american-literature-vol-ii-2004:node/223',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_american-poetry-and-prose-1934:node/137.
  $menu_links['main-menu_american-poetry-and-prose-1934:node/137'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/137',
    'router_path' => 'node/%',
    'link_title' => 'American Poetry and Prose (1934)',
    'options' => array(
      'identifier' => 'main-menu_american-poetry-and-prose-1934:node/137',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_american-women-writers-to-1800-1996:node/201.
  $menu_links['main-menu_american-women-writers-to-1800-1996:node/201'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/201',
    'router_path' => 'node/%',
    'link_title' => 'American Women Writers to 1800 (1996)',
    'options' => array(
      'identifier' => 'main-menu_american-women-writers-to-1800-1996:node/201',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_anthologies--histories:taxonomy/term/29.
  $menu_links['main-menu_anthologies--histories:taxonomy/term/29'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/29',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Anthologies & Histories',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_anthologies--histories:taxonomy/term/29',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -49,
    'customized' => 1,
  );
  // Exported menu link: main-menu_anthology-of-american-literature-teachers-edition-vol-ii-2004:node/221.
  $menu_links['main-menu_anthology-of-american-literature-teachers-edition-vol-ii-2004:node/221'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/221',
    'router_path' => 'node/%',
    'link_title' => 'Anthology of American Literature Teacher\'s Edition, Vol. II (2004)',
    'options' => array(
      'identifier' => 'main-menu_anthology-of-american-literature-teachers-edition-vol-ii-2004:node/221',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_anthology-of-american-literature-vol-1-1974:node/179.
  $menu_links['main-menu_anthology-of-american-literature-vol-1-1974:node/179'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/179',
    'router_path' => 'node/%',
    'link_title' => 'Anthology of American Literature, Vol. 1 (1974)',
    'options' => array(
      'identifier' => 'main-menu_anthology-of-american-literature-vol-1-1974:node/179',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_anthology-of-american-literature-vol-1-2000:node/208.
  $menu_links['main-menu_anthology-of-american-literature-vol-1-2000:node/208'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/208',
    'router_path' => 'node/%',
    'link_title' => 'Anthology of American Literature, Vol. 1 (2000)',
    'options' => array(
      'identifier' => 'main-menu_anthology-of-american-literature-vol-1-2000:node/208',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -30,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_anthology-of-american-literature-vol-1-2004:node/214.
  $menu_links['main-menu_anthology-of-american-literature-vol-1-2004:node/214'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/214',
    'router_path' => 'node/%',
    'link_title' => 'Anthology of American Literature, Vol. 1 (2004)',
    'options' => array(
      'identifier' => 'main-menu_anthology-of-american-literature-vol-1-2004:node/214',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_canons-by-consensus:node/1673.
  $menu_links['main-menu_canons-by-consensus:node/1673'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1673',
    'router_path' => 'node/%',
    'link_title' => 'Canons by Consensus',
    'options' => array(
      'attributes' => array(
        'title' => 'Csicila Bibliography',
      ),
      'identifier' => 'main-menu_canons-by-consensus:node/1673',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
    'parent_identifier' => 'main-menu_other-resources:taxonomy/term/25',
  );
  // Exported menu link: main-menu_century-readings-for-a-course-in-american-literature-1919:node/134.
  $menu_links['main-menu_century-readings-for-a-course-in-american-literature-1919:node/134'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/134',
    'router_path' => 'node/%',
    'link_title' => 'Century Readings for a Course in American Literature (1919)',
    'options' => array(
      'identifier' => 'main-menu_century-readings-for-a-course-in-american-literature-1919:node/134',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_colonial-american-literature-1976:node/180.
  $menu_links['main-menu_colonial-american-literature-1976:node/180'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/180',
    'router_path' => 'node/%',
    'link_title' => 'Colonial American Literature (1976)',
    'options' => array(
      'identifier' => 'main-menu_colonial-american-literature-1976:node/180',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_colonial-american-writing-1950:node/145.
  $menu_links['main-menu_colonial-american-writing-1950:node/145'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/145',
    'router_path' => 'node/%',
    'link_title' => 'Colonial American Writing (1950)',
    'options' => array(
      'identifier' => 'main-menu_colonial-american-writing-1950:node/145',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_colonial-american-writing-1969:node/168.
  $menu_links['main-menu_colonial-american-writing-1969:node/168'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/168',
    'router_path' => 'node/%',
    'link_title' => 'Colonial American Writing (1969)',
    'options' => array(
      'identifier' => 'main-menu_colonial-american-writing-1969:node/168',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_colonial-and-federal-to-1800-1962:node/159.
  $menu_links['main-menu_colonial-and-federal-to-1800-1962:node/159'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/159',
    'router_path' => 'node/%',
    'link_title' => 'Colonial and Federal to 1800 (1962)',
    'options' => array(
      'identifier' => 'main-menu_colonial-and-federal-to-1800-1962:node/159',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_colonial-and-federalist-american-writing-1966:node/166.
  $menu_links['main-menu_colonial-and-federalist-american-writing-1966:node/166'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/166',
    'router_path' => 'node/%',
    'link_title' => 'Colonial and Federalist American Writing (1966)',
    'options' => array(
      'identifier' => 'main-menu_colonial-and-federalist-american-writing-1966:node/166',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_columbia-literary-history-of-the-united-states-1988:node/188.
  $menu_links['main-menu_columbia-literary-history-of-the-united-states-1988:node/188'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/188',
    'router_path' => 'node/%',
    'link_title' => 'Columbia Literary History of the United States (1988)',
    'options' => array(
      'identifier' => 'main-menu_columbia-literary-history-of-the-united-states-1988:node/188',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1981-1990:taxonomy/term/22',
  );
  // Exported menu link: main-menu_cyclopaedia-of-american-literature-vol-i-1855:node/116.
  $menu_links['main-menu_cyclopaedia-of-american-literature-vol-i-1855:node/116'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/116',
    'router_path' => 'node/%',
    'link_title' => 'Cyclopaedia of American Literature, Vol. I (1855)',
    'options' => array(
      'identifier' => 'main-menu_cyclopaedia-of-american-literature-vol-i-1855:node/116',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1801-1860:taxonomy/term/18',
  );
  // Exported menu link: main-menu_cyclopaedia-of-american-literature-vol-ii-1855:node/117.
  $menu_links['main-menu_cyclopaedia-of-american-literature-vol-ii-1855:node/117'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/117',
    'router_path' => 'node/%',
    'link_title' => 'Cyclopaedia of American Literature, Vol. II (1855)',
    'options' => array(
      'identifier' => 'main-menu_cyclopaedia-of-american-literature-vol-ii-1855:node/117',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1801-1860:taxonomy/term/18',
  );
  // Exported menu link: main-menu_early-american-drama-1997:node/202.
  $menu_links['main-menu_early-american-drama-1997:node/202'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/202',
    'router_path' => 'node/%',
    'link_title' => 'Early American Drama (1997)',
    'options' => array(
      'identifier' => 'main-menu_early-american-drama-1997:node/202',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_early-american-poetry-1978:node/181.
  $menu_links['main-menu_early-american-poetry-1978:node/181'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/181',
    'router_path' => 'node/%',
    'link_title' => 'Early American Poetry (1978)',
    'options' => array(
      'identifier' => 'main-menu_early-american-poetry-1978:node/181',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_early-american-writing-1994:node/194.
  $menu_links['main-menu_early-american-writing-1994:node/194'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/194',
    'router_path' => 'node/%',
    'link_title' => 'Early American Writing (1994)',
    'options' => array(
      'identifier' => 'main-menu_early-american-writing-1994:node/194',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_early-american-writings-2002:node/210.
  $menu_links['main-menu_early-american-writings-2002:node/210'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/210',
    'router_path' => 'node/%',
    'link_title' => 'Early American Writings (2002)',
    'options' => array(
      'identifier' => 'main-menu_early-american-writings-2002:node/210',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_eight-american-writers-an-anthology-of-american-literature-1963:node/165.
  $menu_links['main-menu_eight-american-writers-an-anthology-of-american-literature-1963:node/165'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/165',
    'router_path' => 'node/%',
    'link_title' => 'Eight American Writers: An Anthology of American Literature (1963)',
    'options' => array(
      'identifier' => 'main-menu_eight-american-writers-an-anthology-of-american-literature-1963:node/165',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_english-literatures-of-america-1500-1800-1997:node/203.
  $menu_links['main-menu_english-literatures-of-america-1500-1800-1997:node/203'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/203',
    'router_path' => 'node/%',
    'link_title' => 'English Literatures of America, 1500-1800 (1997)',
    'options' => array(
      'identifier' => 'main-menu_english-literatures-of-america-1500-1800-1997:node/203',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_harper-american-literature-vol-1-1987:node/186.
  $menu_links['main-menu_harper-american-literature-vol-1-1987:node/186'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/186',
    'router_path' => 'node/%',
    'link_title' => 'Harper American Literature, Vol. 1 (1987)',
    'options' => array(
      'identifier' => 'main-menu_harper-american-literature-vol-1-1987:node/186',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1981-1990:taxonomy/term/22',
  );
  // Exported menu link: main-menu_harper-american-literature-vol-1-1993:node/195.
  $menu_links['main-menu_harper-american-literature-vol-1-1993:node/195'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/195',
    'router_path' => 'node/%',
    'link_title' => 'Harper American Literature, Vol. 1 (1993)',
    'options' => array(
      'identifier' => 'main-menu_harper-american-literature-vol-1-1993:node/195',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_harper-american-literature-vol-2-1987:node/187.
  $menu_links['main-menu_harper-american-literature-vol-2-1987:node/187'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/187',
    'router_path' => 'node/%',
    'link_title' => 'Harper American Literature, Vol. 2 (1987)',
    'options' => array(
      'identifier' => 'main-menu_harper-american-literature-vol-2-1987:node/187',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1981-1990:taxonomy/term/22',
  );
  // Exported menu link: main-menu_harper-american-literature-vol-2-1993:node/196.
  $menu_links['main-menu_harper-american-literature-vol-2-1993:node/196'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/196',
    'router_path' => 'node/%',
    'link_title' => 'Harper American Literature, Vol. 2 (1993)',
    'options' => array(
      'identifier' => 'main-menu_harper-american-literature-vol-2-1993:node/196',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_home:<front>.
  $menu_links['main-menu_home:<front>'] = array(
    'menu_name' => 'main-menu',
    'link_path' => '<front>',
    'router_path' => '',
    'link_title' => 'Home',
    'options' => array(
      'identifier' => 'main-menu_home:<front>',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 1,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
  );
  // Exported menu link: main-menu_introduction:node/264.
  $menu_links['main-menu_introduction:node/264'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/264',
    'router_path' => 'node/%',
    'link_title' => 'Introduction',
    'options' => array(
      'identifier' => 'main-menu_introduction:node/264',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_about:node/261',
  );
  // Exported menu link: main-menu_lectures-on-american-literature-1829:node/115.
  $menu_links['main-menu_lectures-on-american-literature-1829:node/115'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/115',
    'router_path' => 'node/%',
    'link_title' => 'Lectures on American Literature (1829)',
    'options' => array(
      'identifier' => 'main-menu_lectures-on-american-literature-1829:node/115',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1801-1860:taxonomy/term/18',
  );
  // Exported menu link: main-menu_literary-history-of-the-united-states-1946-1948:node/141.
  $menu_links['main-menu_literary-history-of-the-united-states-1946-1948:node/141'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/141',
    'router_path' => 'node/%',
    'link_title' => 'Literary History of the United States (1946, 1948)',
    'options' => array(
      'identifier' => 'main-menu_literary-history-of-the-united-states-1946-1948:node/141',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_main-currents-in-american-thought-1927:node/135.
  $menu_links['main-menu_main-currents-in-american-thought-1927:node/135'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/135',
    'router_path' => 'node/%',
    'link_title' => 'Main Currents in American Thought (1927)',
    'options' => array(
      'identifier' => 'main-menu_main-currents-in-american-thought-1927:node/135',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_major-american-writers-1952:node/148.
  $menu_links['main-menu_major-american-writers-1952:node/148'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/148',
    'router_path' => 'node/%',
    'link_title' => 'Major American Writers (1952)',
    'options' => array(
      'identifier' => 'main-menu_major-american-writers-1952:node/148',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_major-writers-of-america-vol-1-1962:node/163.
  $menu_links['main-menu_major-writers-of-america-vol-1-1962:node/163'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/163',
    'router_path' => 'node/%',
    'link_title' => 'Major Writers of America, Vol. 1 (1962)',
    'options' => array(
      'identifier' => 'main-menu_major-writers-of-america-vol-1-1962:node/163',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_major-writers-of-america-vol-2-1962:node/164.
  $menu_links['main-menu_major-writers-of-america-vol-2-1962:node/164'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/164',
    'router_path' => 'node/%',
    'link_title' => 'Major Writers of America, Vol. 2 (1962)',
    'options' => array(
      'identifier' => 'main-menu_major-writers-of-america-vol-2-1962:node/164',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_major-writers-of-early-american-literature-critical-essays-1972:node/176.
  $menu_links['main-menu_major-writers-of-early-american-literature-critical-essays-1972:node/176'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/176',
    'router_path' => 'node/%',
    'link_title' => 'Major Writers of Early American Literature, Critical Essays (1972)',
    'options' => array(
      'identifier' => 'main-menu_major-writers-of-early-american-literature-critical-essays-1972:node/176',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_masters-of-american-literature-1959:node/158.
  $menu_links['main-menu_masters-of-american-literature-1959:node/158'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/158',
    'router_path' => 'node/%',
    'link_title' => 'Masters of American Literature (1959)',
    'options' => array(
      'identifier' => 'main-menu_masters-of-american-literature-1959:node/158',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -36,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_masters-of-american-literature-vol-1-1949:node/142.
  $menu_links['main-menu_masters-of-american-literature-vol-1-1949:node/142'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/142',
    'router_path' => 'node/%',
    'link_title' => 'Masters of American Literature, Vol. 1 (1949)',
    'options' => array(
      'identifier' => 'main-menu_masters-of-american-literature-vol-1-1949:node/142',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_masters-of-american-literature-vol-2-1949:node/143.
  $menu_links['main-menu_masters-of-american-literature-vol-2-1949:node/143'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/143',
    'router_path' => 'node/%',
    'link_title' => 'Masters of American Literature, Vol. 2 (1949)',
    'options' => array(
      'identifier' => 'main-menu_masters-of-american-literature-vol-2-1949:node/143',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_o-brave-new-world-american-literature-1600-1840-1968:node/167.
  $menu_links['main-menu_o-brave-new-world-american-literature-1600-1840-1968:node/167'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/167',
    'router_path' => 'node/%',
    'link_title' => 'O Brave New World: American Literature 1600-1840 (1968)',
    'options' => array(
      'identifier' => 'main-menu_o-brave-new-world-american-literature-1600-1840-1968:node/167',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -44,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_other-resources:taxonomy/term/25.
  $menu_links['main-menu_other-resources:taxonomy/term/25'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'taxonomy/term/25',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'Other Resources',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'main-menu_other-resources:taxonomy/term/25',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => -50,
    'customized' => 1,
  );
  // Exported menu link: main-menu_project-staff:node/1672.
  $menu_links['main-menu_project-staff:node/1672'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/1672',
    'router_path' => 'node/%',
    'link_title' => 'Project Staff',
    'options' => array(
      'identifier' => 'main-menu_project-staff:node/1672',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'main-menu_about:node/261',
  );
  // Exported menu link: main-menu_the-american-tradition-in-literature-1994:node/224.
  $menu_links['main-menu_the-american-tradition-in-literature-1994:node/224'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/224',
    'router_path' => 'node/%',
    'link_title' => 'The American Tradition in Literature (1994)',
    'options' => array(
      'identifier' => 'main-menu_the-american-tradition-in-literature-1994:node/224',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-american-tradition-in-literature-vol-1-1956:node/156.
  $menu_links['main-menu_the-american-tradition-in-literature-vol-1-1956:node/156'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/156',
    'router_path' => 'node/%',
    'link_title' => 'The American Tradition in Literature, Vol. 1 (1956)',
    'options' => array(
      'identifier' => 'main-menu_the-american-tradition-in-literature-vol-1-1956:node/156',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-american-tradition-in-literature-vol-2-1956:node/157.
  $menu_links['main-menu_the-american-tradition-in-literature-vol-2-1956:node/157'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/157',
    'router_path' => 'node/%',
    'link_title' => 'The American Tradition in Literature, Vol. 2 (1956)',
    'options' => array(
      'identifier' => 'main-menu_the-american-tradition-in-literature-vol-2-1956:node/157',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-1-1994:node/197.
  $menu_links['main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-1-1994:node/197'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/197',
    'router_path' => 'node/%',
    'link_title' => 'The Cambridge History of American Literature, 1590-1820, Vol. 1 (1994)',
    'options' => array(
      'identifier' => 'main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-1-1994:node/197',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -43,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-2-1994:node/198.
  $menu_links['main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-2-1994:node/198'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/198',
    'router_path' => 'node/%',
    'link_title' => 'The Cambridge History of American Literature, 1590-1820, Vol. 2 (1994)',
    'options' => array(
      'identifier' => 'main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-2-1994:node/198',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -42,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-7-1994:node/199.
  $menu_links['main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-7-1994:node/199'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/199',
    'router_path' => 'node/%',
    'link_title' => 'The Cambridge History of American Literature, 1590-1820, Vol. 7 (1994)',
    'options' => array(
      'identifier' => 'main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-7-1994:node/199',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-8-1994:node/200.
  $menu_links['main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-8-1994:node/200'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/200',
    'router_path' => 'node/%',
    'link_title' => 'The Cambridge History of American Literature, 1590-1820, Vol. 8 (1994)',
    'options' => array(
      'identifier' => 'main-menu_the-cambridge-history-of-american-literature-1590-1820-vol-8-1994:node/200',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-chief-american-prose-writers-1916:node/133.
  $menu_links['main-menu_the-chief-american-prose-writers-1916:node/133'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/133',
    'router_path' => 'node/%',
    'link_title' => 'The Chief American Prose Writers (1916)',
    'options' => array(
      'identifier' => 'main-menu_the-chief-american-prose-writers-1916:node/133',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_the-cycle-of-american-literature-1955:node/153.
  $menu_links['main-menu_the-cycle-of-american-literature-1955:node/153'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/153',
    'router_path' => 'node/%',
    'link_title' => 'The Cycle of American Literature (1955)',
    'options' => array(
      'identifier' => 'main-menu_the-cycle-of-american-literature-1955:node/153',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-first-century-of-american-literature-1770-1870-1935-1966:node/138.
  $menu_links['main-menu_the-first-century-of-american-literature-1770-1870-1935-1966:node/138'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/138',
    'router_path' => 'node/%',
    'link_title' => 'The First Century of American Literature, 1770-1870 (1935, 1966)',
    'options' => array(
      'identifier' => 'main-menu_the-first-century-of-american-literature-1770-1870-1935-1966:node/138',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1901-1950:taxonomy/term/14',
  );
  // Exported menu link: main-menu_the-growth-of-american-literature-vol-1-1956:node/154.
  $menu_links['main-menu_the-growth-of-american-literature-vol-1-1956:node/154'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/154',
    'router_path' => 'node/%',
    'link_title' => 'The Growth of American Literature, Vol. 1 (1956)',
    'options' => array(
      'identifier' => 'main-menu_the-growth-of-american-literature-vol-1-1956:node/154',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-growth-of-american-literature-vol-2-1956:node/155.
  $menu_links['main-menu_the-growth-of-american-literature-vol-2-1956:node/155'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/155',
    'router_path' => 'node/%',
    'link_title' => 'The Growth of American Literature, Vol. 2 (1956)',
    'options' => array(
      'identifier' => 'main-menu_the-growth-of-american-literature-vol-2-1956:node/155',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-harper-single-volume-american-literature-1999:node/226.
  $menu_links['main-menu_the-harper-single-volume-american-literature-1999:node/226'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/226',
    'router_path' => 'node/%',
    'link_title' => 'The Harper Single Volume American Literature (1999)',
    'options' => array(
      'identifier' => 'main-menu_the-harper-single-volume-american-literature-1999:node/226',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -32,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-2004:node/215.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-2004:node/215'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/215',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature (2004)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-2004:node/215',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-1-1990:node/189.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-1-1990:node/189'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/189',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. 1 (1990)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-1-1990:node/189',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1981-1990:taxonomy/term/22',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-1-1998:node/204.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-1-1998:node/204'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/204',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. 1 (1998)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-1-1998:node/204',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -36,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-1-2002:node/211.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-1-2002:node/211'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/211',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. 1 (2002)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-1-2002:node/211',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-2-1990:node/190.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-2-1990:node/190'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/190',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. 2 (1990)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-2-1990:node/190',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1981-1990:taxonomy/term/22',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-2-1998:node/205.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-2-1998:node/205'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/205',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. 2 (1998)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-2-1998:node/205',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -35,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-2-2002:node/212.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-2-2002:node/212'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/212',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. 2 (2002)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-2-2002:node/212',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-a-2006:node/216.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-a-2006:node/216'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/216',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. A (2006)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-a-2006:node/216',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -39,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-b-2006:node/217.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-b-2006:node/217'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/217',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. B (2006)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-b-2006:node/217',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -38,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-c-2006:node/218.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-c-2006:node/218'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/218',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. C (2006)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-c-2006:node/218',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-d-2006:node/219.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-d-2006:node/219'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/219',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. D (2006)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-d-2006:node/219',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -36,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heath-anthology-of-american-literature-vol-e-2006:node/225.
  $menu_links['main-menu_the-heath-anthology-of-american-literature-vol-e-2006:node/225'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/225',
    'router_path' => 'node/%',
    'link_title' => 'The Heath Anthology of American Literature, Vol. E (2006)',
    'options' => array(
      'identifier' => 'main-menu_the-heath-anthology-of-american-literature-vol-e-2006:node/225',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -35,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-heritage-of-american-literature-vol-1-1951:node/146.
  $menu_links['main-menu_the-heritage-of-american-literature-vol-1-1951:node/146'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/146',
    'router_path' => 'node/%',
    'link_title' => 'The Heritage of American Literature, Vol. 1 (1951)',
    'options' => array(
      'identifier' => 'main-menu_the-heritage-of-american-literature-vol-1-1951:node/146',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-heritage-of-american-literature-vol-2-1951:node/147.
  $menu_links['main-menu_the-heritage-of-american-literature-vol-2-1951:node/147'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/147',
    'router_path' => 'node/%',
    'link_title' => 'The Heritage of American Literature, Vol. 2 (1951)',
    'options' => array(
      'identifier' => 'main-menu_the-heritage-of-american-literature-vol-2-1951:node/147',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-literature-of-america-colonial-period-1970:node/174.
  $menu_links['main-menu_the-literature-of-america-colonial-period-1970:node/174'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/174',
    'router_path' => 'node/%',
    'link_title' => 'The Literature of America: Colonial Period (1970)',
    'options' => array(
      'identifier' => 'main-menu_the-literature-of-america-colonial-period-1970:node/174',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -37,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_the-literature-of-the-united-states-vol-1-1953:node/149.
  $menu_links['main-menu_the-literature-of-the-united-states-vol-1-1953:node/149'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/149',
    'router_path' => 'node/%',
    'link_title' => 'The Literature of the United States, Vol. 1 (1953)',
    'options' => array(
      'identifier' => 'main-menu_the-literature-of-the-united-states-vol-1-1953:node/149',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-literature-of-the-united-states-vol-2-1953:node/150.
  $menu_links['main-menu_the-literature-of-the-united-states-vol-2-1953:node/150'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/150',
    'router_path' => 'node/%',
    'link_title' => 'The Literature of the United States, Vol. 2 (1953)',
    'options' => array(
      'identifier' => 'main-menu_the-literature-of-the-united-states-vol-2-1953:node/150',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -46,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1951-1960:taxonomy/term/15',
  );
  // Exported menu link: main-menu_the-literatures-of-colonial-america-2001:node/209.
  $menu_links['main-menu_the-literatures-of-colonial-america-2001:node/209'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/209',
    'router_path' => 'node/%',
    'link_title' => 'The Literatures of Colonial America (2001)',
    'options' => array(
      'identifier' => 'main-menu_the-literatures-of-colonial-america-2001:node/209',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-meridian-anthology-of-early-american-women-writers-1991:node/193.
  $menu_links['main-menu_the-meridian-anthology-of-early-american-women-writers-1991:node/193'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/193',
    'router_path' => 'node/%',
    'link_title' => 'The Meridian Anthology of Early American Women Writers (1991)',
    'options' => array(
      'identifier' => 'main-menu_the-meridian-anthology-of-early-american-women-writers-1991:node/193',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -48,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-new-anthology-of-american-poetry-vol-1-2003:node/213.
  $menu_links['main-menu_the-new-anthology-of-american-poetry-vol-1-2003:node/213'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/213',
    'router_path' => 'node/%',
    'link_title' => 'The New Anthology of American Poetry, Vol. 1 (2003)',
    'options' => array(
      'identifier' => 'main-menu_the-new-anthology-of-american-poetry-vol-1-2003:node/213',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -45,
    'customized' => 1,
    'parent_identifier' => 'main-menu_2001-:taxonomy/term/17',
  );
  // Exported menu link: main-menu_the-norton-anthology-of-american-literature-vol-1-1979:node/184.
  $menu_links['main-menu_the-norton-anthology-of-american-literature-vol-1-1979:node/184'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/184',
    'router_path' => 'node/%',
    'link_title' => 'The Norton Anthology of American Literature, Vol. 1 (1979)',
    'options' => array(
      'identifier' => 'main-menu_the-norton-anthology-of-american-literature-vol-1-1979:node/184',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -41,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_the-norton-anthology-of-american-literature-vol-1-1998:node/206.
  $menu_links['main-menu_the-norton-anthology-of-american-literature-vol-1-1998:node/206'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/206',
    'router_path' => 'node/%',
    'link_title' => 'The Norton Anthology of American Literature, Vol. 1 (1998)',
    'options' => array(
      'identifier' => 'main-menu_the-norton-anthology-of-american-literature-vol-1-1998:node/206',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -34,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_the-norton-anthology-of-american-literature-vol-2-1979:node/185.
  $menu_links['main-menu_the-norton-anthology-of-american-literature-vol-2-1979:node/185'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/185',
    'router_path' => 'node/%',
    'link_title' => 'The Norton Anthology of American Literature, Vol. 2 (1979)',
    'options' => array(
      'identifier' => 'main-menu_the-norton-anthology-of-american-literature-vol-2-1979:node/185',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -40,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: main-menu_the-norton-anthology-of-american-literature-vol-2-1998:node/207.
  $menu_links['main-menu_the-norton-anthology-of-american-literature-vol-2-1998:node/207'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/207',
    'router_path' => 'node/%',
    'link_title' => 'The Norton Anthology of American Literature, Vol. 2 (1998)',
    'options' => array(
      'identifier' => 'main-menu_the-norton-anthology-of-american-literature-vol-2-1998:node/207',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -33,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_three-centuries-of-american-poetry-1620-1923-1999:node/220.
  $menu_links['main-menu_three-centuries-of-american-poetry-1620-1923-1999:node/220'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/220',
    'router_path' => 'node/%',
    'link_title' => 'Three Centuries of American Poetry 1620-1923 (1999)',
    'options' => array(
      'identifier' => 'main-menu_three-centuries-of-american-poetry-1620-1923-1999:node/220',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -31,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1991-2000:taxonomy/term/16',
  );
  // Exported menu link: main-menu_twelve-american-writers-1962:node/162.
  $menu_links['main-menu_twelve-american-writers-1962:node/162'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/162',
    'router_path' => 'node/%',
    'link_title' => 'Twelve American Writers (1962)',
    'options' => array(
      'identifier' => 'main-menu_twelve-american-writers-1962:node/162',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -47,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1961-1970:taxonomy/term/20',
  );
  // Exported menu link: main-menu_who-are-the-major-american-writers-1972:node/175.
  $menu_links['main-menu_who-are-the-major-american-writers-1972:node/175'] = array(
    'menu_name' => 'main-menu',
    'link_path' => 'node/175',
    'router_path' => 'node/%',
    'link_title' => 'Who are the Major American Writers? (1972)',
    'options' => array(
      'identifier' => 'main-menu_who-are-the-major-american-writers-1972:node/175',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -49,
    'customized' => 1,
    'parent_identifier' => 'main-menu_1971-1980:taxonomy/term/21',
  );
  // Exported menu link: management_about-menu:admin/structure/menu/manage/menu-about.
  $menu_links['management_about-menu:admin/structure/menu/manage/menu-about'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/menu/manage/menu-about',
    'router_path' => 'admin/structure/menu/manage/%',
    'link_title' => 'About Menu',
    'options' => array(
      'identifier' => 'management_about-menu:admin/structure/menu/manage/menu-about',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_menus:admin/structure/menu',
  );
  // Exported menu link: management_account-settings:admin/config/people/accounts.
  $menu_links['management_account-settings:admin/config/people/accounts'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/people/accounts',
    'router_path' => 'admin/config/people/accounts',
    'link_title' => 'Account settings',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure default behavior of users, including registration requirements, e-mails, fields, and user pictures.',
      ),
      'identifier' => 'management_account-settings:admin/config/people/accounts',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_people:admin/config/people',
  );
  // Exported menu link: management_actions:admin/config/system/actions.
  $menu_links['management_actions:admin/config/system/actions'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/actions',
    'router_path' => 'admin/config/system/actions',
    'link_title' => 'Actions',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage the actions defined for your site.',
      ),
      'identifier' => 'management_actions:admin/config/system/actions',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_administration-menu:admin/config/administration/admin_menu.
  $menu_links['management_administration-menu:admin/config/administration/admin_menu'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/administration/admin_menu',
    'router_path' => 'admin/config/administration/admin_menu',
    'link_title' => 'Administration menu',
    'options' => array(
      'attributes' => array(
        'title' => 'Adjust administration menu settings.',
      ),
      'identifier' => 'management_administration-menu:admin/config/administration/admin_menu',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin/config/administration',
  );
  // Exported menu link: management_administration:admin.
  $menu_links['management_administration:admin'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin',
    'router_path' => 'admin',
    'link_title' => 'Administration',
    'options' => array(
      'identifier' => 'management_administration:admin',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 9,
    'customized' => 0,
  );
  // Exported menu link: management_administration:admin/config/administration.
  $menu_links['management_administration:admin/config/administration'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/administration',
    'router_path' => 'admin/config/administration',
    'link_title' => 'Administration',
    'options' => array(
      'attributes' => array(
        'title' => 'Administration tools.',
      ),
      'identifier' => 'management_administration:admin/config/administration',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_appearance:admin/appearance.
  $menu_links['management_appearance:admin/appearance'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/appearance',
    'router_path' => 'admin/appearance',
    'link_title' => 'Appearance',
    'options' => array(
      'attributes' => array(
        'title' => 'Select and configure your themes.',
      ),
      'identifier' => 'management_appearance:admin/appearance',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -6,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_automatic-label:admin/structure/auto-label.
  $menu_links['management_automatic-label:admin/structure/auto-label'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/auto-label',
    'router_path' => 'admin/structure/auto-label',
    'link_title' => 'Automatic label',
    'options' => array(
      'identifier' => 'management_automatic-label:admin/structure/auto-label',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_available-updates:admin/reports/updates.
  $menu_links['management_available-updates:admin/reports/updates'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/updates',
    'router_path' => 'admin/reports/updates',
    'link_title' => 'Available updates',
    'options' => array(
      'attributes' => array(
        'title' => 'Get a status report about available updates for your installed modules and themes.',
      ),
      'identifier' => 'management_available-updates:admin/reports/updates',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -50,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_back-to-top:admin/config/user-interface/back_to_top.
  $menu_links['management_back-to-top:admin/config/user-interface/back_to_top'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/user-interface/back_to_top',
    'router_path' => 'admin/config/user-interface/back_to_top',
    'link_title' => 'Back To Top',
    'options' => array(
      'attributes' => array(
        'title' => 'Administer Back To Top settings',
      ),
      'identifier' => 'management_back-to-top:admin/config/user-interface/back_to_top',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_user-interface:admin/config/user-interface',
  );
  // Exported menu link: management_backup-and-migrate:admin/config/system/backup_migrate.
  $menu_links['management_backup-and-migrate:admin/config/system/backup_migrate'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/backup_migrate',
    'router_path' => 'admin/config/system/backup_migrate',
    'link_title' => 'Backup and Migrate',
    'options' => array(
      'attributes' => array(
        'title' => 'Backup/restore your database and files or migrate data to or from another Drupal site.',
      ),
      'identifier' => 'management_backup-and-migrate:admin/config/system/backup_migrate',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_blocks:admin/structure/block.
  $menu_links['management_blocks:admin/structure/block'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/block',
    'router_path' => 'admin/structure/block',
    'link_title' => 'Blocks',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure what block content appears in your site\'s sidebars and other regions.',
      ),
      'identifier' => 'management_blocks:admin/structure/block',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_bulk-exporter:admin/structure/bulk-export.
  $menu_links['management_bulk-exporter:admin/structure/bulk-export'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/bulk-export',
    'router_path' => 'admin/structure/bulk-export',
    'link_title' => 'Bulk Exporter',
    'options' => array(
      'attributes' => array(
        'title' => 'Bulk-export multiple CTools-handled data objects to code.',
      ),
      'identifier' => 'management_bulk-exporter:admin/structure/bulk-export',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_ckeditor:admin/config/content/ckeditor.
  $menu_links['management_ckeditor:admin/config/content/ckeditor'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/content/ckeditor',
    'router_path' => 'admin/config/content/ckeditor',
    'link_title' => 'CKEditor',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure the rich text editor.',
      ),
      'identifier' => 'management_ckeditor:admin/config/content/ckeditor',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_content-authoring:admin/config/content',
  );
  // Exported menu link: management_clean-urls:admin/config/search/clean-urls.
  $menu_links['management_clean-urls:admin/config/search/clean-urls'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/search/clean-urls',
    'router_path' => 'admin/config/search/clean-urls',
    'link_title' => 'Clean URLs',
    'options' => array(
      'attributes' => array(
        'title' => 'Enable or disable clean URLs for your site.',
      ),
      'identifier' => 'management_clean-urls:admin/config/search/clean-urls',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'parent_identifier' => 'management_search-and-metadata:admin/config/search',
  );
  // Exported menu link: management_comments:admin/content/comment.
  $menu_links['management_comments:admin/content/comment'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/content/comment',
    'router_path' => 'admin/content/comment',
    'link_title' => 'Comments',
    'options' => array(
      'attributes' => array(
        'title' => 'List and edit site comments and the comment approval queue.',
      ),
      'identifier' => 'management_comments:admin/content/comment',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_content:admin/content',
  );
  // Exported menu link: management_configuration:admin/config.
  $menu_links['management_configuration:admin/config'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config',
    'router_path' => 'admin/config',
    'link_title' => 'Configuration',
    'options' => array(
      'attributes' => array(
        'title' => 'Administer settings.',
      ),
      'identifier' => 'management_configuration:admin/config',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_content-authoring:admin/config/content.
  $menu_links['management_content-authoring:admin/config/content'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/content',
    'router_path' => 'admin/config/content',
    'link_title' => 'Content authoring',
    'options' => array(
      'attributes' => array(
        'title' => 'Settings related to formatting and authoring content.',
      ),
      'identifier' => 'management_content-authoring:admin/config/content',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -15,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_content-types:admin/structure/types.
  $menu_links['management_content-types:admin/structure/types'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/types',
    'router_path' => 'admin/structure/types',
    'link_title' => 'Content types',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage content types, including default status, front page promotion, comment settings, etc.',
      ),
      'identifier' => 'management_content-types:admin/structure/types',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_content:admin/content.
  $menu_links['management_content:admin/content'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/content',
    'router_path' => 'admin/content',
    'link_title' => 'Content',
    'options' => array(
      'attributes' => array(
        'title' => 'Administer content and comments.',
      ),
      'identifier' => 'management_content:admin/content',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_cron:admin/config/system/cron.
  $menu_links['management_cron:admin/config/system/cron'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/cron',
    'router_path' => 'admin/config/system/cron',
    'link_title' => 'Cron',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage automatic site maintenance tasks.',
      ),
      'identifier' => 'management_cron:admin/config/system/cron',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 20,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_current-search-blocks:admin/config/search/current_search.
  $menu_links['management_current-search-blocks:admin/config/search/current_search'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/search/current_search',
    'router_path' => 'admin/config/search/current_search',
    'link_title' => 'Current search blocks',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure current search blocks.',
      ),
      'identifier' => 'management_current-search-blocks:admin/config/search/current_search',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_search-and-metadata:admin/config/search',
  );
  // Exported menu link: management_dashboard:admin/dashboard.
  $menu_links['management_dashboard:admin/dashboard'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/dashboard',
    'router_path' => 'admin/dashboard',
    'link_title' => 'Dashboard',
    'options' => array(
      'attributes' => array(
        'title' => 'View and customize your dashboard.',
      ),
      'identifier' => 'management_dashboard:admin/dashboard',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -15,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_data-export-import:admin/config/system/data_export_import.
  $menu_links['management_data-export-import:admin/config/system/data_export_import'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/data_export_import',
    'router_path' => 'admin/config/system/data_export_import',
    'link_title' => 'Data export import',
    'options' => array(
      'attributes' => array(
        'title' => 'Data export import',
      ),
      'identifier' => 'management_data-export-import:admin/config/system/data_export_import',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_date-and-time:admin/config/regional/date-time.
  $menu_links['management_date-and-time:admin/config/regional/date-time'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/regional/date-time',
    'router_path' => 'admin/config/regional/date-time',
    'link_title' => 'Date and time',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure display formats for date and time.',
      ),
      'identifier' => 'management_date-and-time:admin/config/regional/date-time',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -15,
    'customized' => 0,
    'parent_identifier' => 'management_regional-and-language:admin/config/regional',
  );
  // Exported menu link: management_date-api:admin/config/date.
  $menu_links['management_date-api:admin/config/date'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/date',
    'router_path' => 'admin/config/date',
    'link_title' => 'Date API',
    'options' => array(
      'attributes' => array(
        'title' => 'Settings for modules the use the Date API.',
      ),
      'identifier' => 'management_date-api:admin/config/date',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_date-tools:admin/config/date/tools.
  $menu_links['management_date-tools:admin/config/date/tools'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/date/tools',
    'router_path' => 'admin/config/date/tools',
    'link_title' => 'Date Tools',
    'options' => array(
      'attributes' => array(
        'title' => 'Date Wizard and other tools to manage and create dates and calendars. ',
      ),
      'identifier' => 'management_date-tools:admin/config/date/tools',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_date-api:admin/config/date',
  );
  // Exported menu link: management_development:admin/config/development.
  $menu_links['management_development:admin/config/development'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/development',
    'router_path' => 'admin/config/development',
    'link_title' => 'Development',
    'options' => array(
      'attributes' => array(
        'title' => 'Development tools.',
      ),
      'identifier' => 'management_development:admin/config/development',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_features:admin/structure/features.
  $menu_links['management_features:admin/structure/features'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/features',
    'router_path' => 'admin/structure/features',
    'link_title' => 'Features',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage features.',
      ),
      'identifier' => 'management_features:admin/structure/features',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_field-list:admin/reports/fields.
  $menu_links['management_field-list:admin/reports/fields'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/fields',
    'router_path' => 'admin/reports/fields',
    'link_title' => 'Field list',
    'options' => array(
      'attributes' => array(
        'title' => 'Overview of fields on all entity types.',
      ),
      'identifier' => 'management_field-list:admin/reports/fields',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_file-settings:admin/config/media/file-settings.
  $menu_links['management_file-settings:admin/config/media/file-settings'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/file-settings',
    'router_path' => 'admin/config/media/file-settings',
    'link_title' => 'File settings',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure allowed file extensions, default alt and title sources, and the file upload wizard.',
      ),
      'identifier' => 'management_file-settings:admin/config/media/file-settings',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_file-system:admin/config/media/file-system.
  $menu_links['management_file-system:admin/config/media/file-system'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/file-system',
    'router_path' => 'admin/config/media/file-system',
    'link_title' => 'File system',
    'options' => array(
      'attributes' => array(
        'title' => 'Tell Drupal where to store uploaded files and how they are accessed.',
      ),
      'identifier' => 'management_file-system:admin/config/media/file-system',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_file-types:admin/structure/file-types.
  $menu_links['management_file-types:admin/structure/file-types'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/file-types',
    'router_path' => 'admin/structure/file-types',
    'link_title' => 'File types',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage settings for the type of files used on your site.',
      ),
      'identifier' => 'management_file-types:admin/structure/file-types',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_help:admin/help.
  $menu_links['management_help:admin/help'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/help',
    'router_path' => 'admin/help',
    'link_title' => 'Help',
    'options' => array(
      'attributes' => array(
        'title' => 'Reference for usage, configuration, and modules.',
      ),
      'identifier' => 'management_help:admin/help',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 9,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_image-styles:admin/config/media/image-styles.
  $menu_links['management_image-styles:admin/config/media/image-styles'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/image-styles',
    'router_path' => 'admin/config/media/image-styles',
    'link_title' => 'Image styles',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure styles that can be used for resizing or adjusting images on display.',
      ),
      'identifier' => 'management_image-styles:admin/config/media/image-styles',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_image-toolkit:admin/config/media/image-toolkit.
  $menu_links['management_image-toolkit:admin/config/media/image-toolkit'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/image-toolkit',
    'router_path' => 'admin/config/media/image-toolkit',
    'link_title' => 'Image toolkit',
    'options' => array(
      'attributes' => array(
        'title' => 'Choose which image toolkit to use if you have installed optional toolkits.',
      ),
      'identifier' => 'management_image-toolkit:admin/config/media/image-toolkit',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 20,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_imce:admin/config/media/imce.
  $menu_links['management_imce:admin/config/media/imce'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/imce',
    'router_path' => 'admin/config/media/imce',
    'link_title' => 'IMCE',
    'options' => array(
      'attributes' => array(
        'title' => 'Control how your image/file browser works.',
      ),
      'identifier' => 'management_imce:admin/config/media/imce',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_ip-address-blocking:admin/config/people/ip-blocking.
  $menu_links['management_ip-address-blocking:admin/config/people/ip-blocking'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/people/ip-blocking',
    'router_path' => 'admin/config/people/ip-blocking',
    'link_title' => 'IP address blocking',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage blocked IP addresses.',
      ),
      'identifier' => 'management_ip-address-blocking:admin/config/people/ip-blocking',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 10,
    'customized' => 0,
    'parent_identifier' => 'management_people:admin/config/people',
  );
  // Exported menu link: management_jquery-update:admin/config/development/jquery_update.
  $menu_links['management_jquery-update:admin/config/development/jquery_update'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/development/jquery_update',
    'router_path' => 'admin/config/development/jquery_update',
    'link_title' => 'jQuery Update',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure settings related to the jQuery upgrade, the library path and compression.',
      ),
      'identifier' => 'management_jquery-update:admin/config/development/jquery_update',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_development:admin/config/development',
  );
  // Exported menu link: management_logging-and-errors:admin/config/development/logging.
  $menu_links['management_logging-and-errors:admin/config/development/logging'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/development/logging',
    'router_path' => 'admin/config/development/logging',
    'link_title' => 'Logging and errors',
    'options' => array(
      'attributes' => array(
        'title' => 'Settings for logging and alerts modules. Various modules can route Drupal\'s system events to different destinations, such as syslog, database, email, etc.',
      ),
      'identifier' => 'management_logging-and-errors:admin/config/development/logging',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -15,
    'customized' => 0,
    'parent_identifier' => 'management_development:admin/config/development',
  );
  // Exported menu link: management_main-menu:admin/structure/menu/manage/main-menu.
  $menu_links['management_main-menu:admin/structure/menu/manage/main-menu'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/menu/manage/main-menu',
    'router_path' => 'admin/structure/menu/manage/%',
    'link_title' => 'Main menu',
    'options' => array(
      'identifier' => 'management_main-menu:admin/structure/menu/manage/main-menu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_menus:admin/structure/menu',
  );
  // Exported menu link: management_maintenance-mode:admin/config/development/maintenance.
  $menu_links['management_maintenance-mode:admin/config/development/maintenance'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/development/maintenance',
    'router_path' => 'admin/config/development/maintenance',
    'link_title' => 'Maintenance mode',
    'options' => array(
      'attributes' => array(
        'title' => 'Take the site offline for maintenance or bring it back online.',
      ),
      'identifier' => 'management_maintenance-mode:admin/config/development/maintenance',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_development:admin/config/development',
  );
  // Exported menu link: management_management:admin/structure/menu/manage/management.
  $menu_links['management_management:admin/structure/menu/manage/management'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/menu/manage/management',
    'router_path' => 'admin/structure/menu/manage/%',
    'link_title' => 'Management',
    'options' => array(
      'identifier' => 'management_management:admin/structure/menu/manage/management',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_menus:admin/structure/menu',
  );
  // Exported menu link: management_media-browser-plus-settings:admin/config/media/media_browser_plus_settings.
  $menu_links['management_media-browser-plus-settings:admin/config/media/media_browser_plus_settings'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/media_browser_plus_settings',
    'router_path' => 'admin/config/media/media_browser_plus_settings',
    'link_title' => 'Media Browser Plus Settings',
    'options' => array(
      'attributes' => array(
        'title' => 'Change the behaviour and layout of the media browser plus UI',
      ),
      'identifier' => 'management_media-browser-plus-settings:admin/config/media/media_browser_plus_settings',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_media-browser-settings:admin/config/media/browser.
  $menu_links['management_media-browser-settings:admin/config/media/browser'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media/browser',
    'router_path' => 'admin/config/media/browser',
    'link_title' => 'Media browser settings',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure the behavior and display of the media browser.',
      ),
      'identifier' => 'management_media-browser-settings:admin/config/media/browser',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_media:admin/config/media',
  );
  // Exported menu link: management_media:admin/config/media.
  $menu_links['management_media:admin/config/media'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/media',
    'router_path' => 'admin/config/media',
    'link_title' => 'Media',
    'options' => array(
      'attributes' => array(
        'title' => 'Media tools.',
      ),
      'identifier' => 'management_media:admin/config/media',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_menus:admin/structure/menu.
  $menu_links['management_menus:admin/structure/menu'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/menu',
    'router_path' => 'admin/structure/menu',
    'link_title' => 'Menus',
    'options' => array(
      'attributes' => array(
        'title' => 'Add new menus to your site, edit existing menus, and rename and reorganize menu links.',
      ),
      'identifier' => 'management_menus:admin/structure/menu',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_mini-panels:admin/structure/mini-panels.
  $menu_links['management_mini-panels:admin/structure/mini-panels'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/mini-panels',
    'router_path' => 'admin/structure/mini-panels',
    'link_title' => 'Mini panels',
    'options' => array(
      'attributes' => array(
        'title' => 'Add, edit or delete mini panels, which can be used as blocks or content panes in other panels.',
      ),
      'identifier' => 'management_mini-panels:admin/structure/mini-panels',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_module-filter:admin/config/user-interface/modulefilter.
  $menu_links['management_module-filter:admin/config/user-interface/modulefilter'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/user-interface/modulefilter',
    'router_path' => 'admin/config/user-interface/modulefilter',
    'link_title' => 'Module filter',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure how the modules page looks and acts.',
      ),
      'identifier' => 'management_module-filter:admin/config/user-interface/modulefilter',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_user-interface:admin/config/user-interface',
  );
  // Exported menu link: management_modules:admin/modules.
  $menu_links['management_modules:admin/modules'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/modules',
    'router_path' => 'admin/modules',
    'link_title' => 'Modules',
    'options' => array(
      'attributes' => array(
        'title' => 'Extend site functionality.',
      ),
      'identifier' => 'management_modules:admin/modules',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -2,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_navigation:admin/structure/menu/manage/navigation.
  $menu_links['management_navigation:admin/structure/menu/manage/navigation'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/menu/manage/navigation',
    'router_path' => 'admin/structure/menu/manage/%',
    'link_title' => 'Navigation',
    'options' => array(
      'identifier' => 'management_navigation:admin/structure/menu/manage/navigation',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_menus:admin/structure/menu',
  );
  // Exported menu link: management_node-export:admin/config/content/node_export.
  $menu_links['management_node-export:admin/config/content/node_export'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/content/node_export',
    'router_path' => 'admin/config/content/node_export',
    'link_title' => 'Node export',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure the settings for Node export.',
      ),
      'identifier' => 'management_node-export:admin/config/content/node_export',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_content-authoring:admin/config/content',
  );
  // Exported menu link: management_pages:admin/structure/pages.
  $menu_links['management_pages:admin/structure/pages'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/pages',
    'router_path' => 'admin/structure/pages',
    'link_title' => 'Pages',
    'options' => array(
      'attributes' => array(
        'title' => 'Add, edit and remove overridden system pages and user defined pages from the system.',
      ),
      'identifier' => 'management_pages:admin/structure/pages',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_panels:admin/structure/panels.
  $menu_links['management_panels:admin/structure/panels'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/panels',
    'router_path' => 'admin/structure/panels',
    'link_title' => 'Panels',
    'options' => array(
      'attributes' => array(
        'title' => 'Get a bird\'s eye view of items related to Panels.',
      ),
      'identifier' => 'management_panels:admin/structure/panels',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_people:admin/config/people.
  $menu_links['management_people:admin/config/people'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/people',
    'router_path' => 'admin/config/people',
    'link_title' => 'People',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure user accounts.',
      ),
      'identifier' => 'management_people:admin/config/people',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -20,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_people:admin/people.
  $menu_links['management_people:admin/people'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/people',
    'router_path' => 'admin/people',
    'link_title' => 'People',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage user accounts, roles, and permissions.',
      ),
      'identifier' => 'management_people:admin/people',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -4,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_performance:admin/config/development/performance.
  $menu_links['management_performance:admin/config/development/performance'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/development/performance',
    'router_path' => 'admin/config/development/performance',
    'link_title' => 'Performance',
    'options' => array(
      'attributes' => array(
        'title' => 'Enable or disable page caching for anonymous users and set CSS and JS bandwidth optimization options.',
      ),
      'identifier' => 'management_performance:admin/config/development/performance',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -20,
    'customized' => 0,
    'parent_identifier' => 'management_development:admin/config/development',
  );
  // Exported menu link: management_recent-hits:admin/reports/hits.
  $menu_links['management_recent-hits:admin/reports/hits'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/hits',
    'router_path' => 'admin/reports/hits',
    'link_title' => 'Recent hits',
    'options' => array(
      'attributes' => array(
        'title' => 'View pages that have recently been visited.',
      ),
      'identifier' => 'management_recent-hits:admin/reports/hits',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_recent-log-messages:admin/reports/dblog.
  $menu_links['management_recent-log-messages:admin/reports/dblog'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/dblog',
    'router_path' => 'admin/reports/dblog',
    'link_title' => 'Recent log messages',
    'options' => array(
      'attributes' => array(
        'title' => 'View events that have recently been logged.',
      ),
      'identifier' => 'management_recent-log-messages:admin/reports/dblog',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -1,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_regional-and-language:admin/config/regional.
  $menu_links['management_regional-and-language:admin/config/regional'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/regional',
    'router_path' => 'admin/config/regional',
    'link_title' => 'Regional and language',
    'options' => array(
      'attributes' => array(
        'title' => 'Regional settings, localization and translation.',
      ),
      'identifier' => 'management_regional-and-language:admin/config/regional',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -5,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_regional-settings:admin/config/regional/settings.
  $menu_links['management_regional-settings:admin/config/regional/settings'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/regional/settings',
    'router_path' => 'admin/config/regional/settings',
    'link_title' => 'Regional settings',
    'options' => array(
      'attributes' => array(
        'title' => 'Settings for the site\'s default time zone and country.',
      ),
      'identifier' => 'management_regional-settings:admin/config/regional/settings',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -20,
    'customized' => 0,
    'parent_identifier' => 'management_regional-and-language:admin/config/regional',
  );
  // Exported menu link: management_reports:admin/reports.
  $menu_links['management_reports:admin/reports'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports',
    'router_path' => 'admin/reports',
    'link_title' => 'Reports',
    'options' => array(
      'attributes' => array(
        'title' => 'View reports, updates, and errors.',
      ),
      'identifier' => 'management_reports:admin/reports',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_rss-publishing:admin/config/services/rss-publishing.
  $menu_links['management_rss-publishing:admin/config/services/rss-publishing'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/services/rss-publishing',
    'router_path' => 'admin/config/services/rss-publishing',
    'link_title' => 'RSS publishing',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure the site description, the number of items per feed and whether feeds should be titles/teasers/full-text.',
      ),
      'identifier' => 'management_rss-publishing:admin/config/services/rss-publishing',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_web-services:admin/config/services',
  );
  // Exported menu link: management_search-and-metadata:admin/config/search.
  $menu_links['management_search-and-metadata:admin/config/search'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/search',
    'router_path' => 'admin/config/search',
    'link_title' => 'Search and metadata',
    'options' => array(
      'attributes' => array(
        'title' => 'Local site search, metadata and SEO.',
      ),
      'identifier' => 'management_search-and-metadata:admin/config/search',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_search-api:admin/config/search/search_api.
  $menu_links['management_search-api:admin/config/search/search_api'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/search/search_api',
    'router_path' => 'admin/config/search/search_api',
    'link_title' => 'Search API',
    'options' => array(
      'attributes' => array(
        'title' => 'Create and configure search engines.',
      ),
      'identifier' => 'management_search-api:admin/config/search/search_api',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_search-and-metadata:admin/config/search',
  );
  // Exported menu link: management_shortcuts:admin/config/user-interface/shortcut.
  $menu_links['management_shortcuts:admin/config/user-interface/shortcut'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/user-interface/shortcut',
    'router_path' => 'admin/config/user-interface/shortcut',
    'link_title' => 'Shortcuts',
    'options' => array(
      'attributes' => array(
        'title' => 'Add and modify shortcut sets.',
      ),
      'identifier' => 'management_shortcuts:admin/config/user-interface/shortcut',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_user-interface:admin/config/user-interface',
  );
  // Exported menu link: management_site-information:admin/config/system/site-information.
  $menu_links['management_site-information:admin/config/system/site-information'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/site-information',
    'router_path' => 'admin/config/system/site-information',
    'link_title' => 'Site information',
    'options' => array(
      'attributes' => array(
        'title' => 'Change site name, e-mail address, slogan, default front page, and number of posts per page, error pages.',
      ),
      'identifier' => 'management_site-information:admin/config/system/site-information',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -20,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_statistics:admin/config/system/statistics.
  $menu_links['management_statistics:admin/config/system/statistics'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/statistics',
    'router_path' => 'admin/config/system/statistics',
    'link_title' => 'Statistics',
    'options' => array(
      'attributes' => array(
        'title' => 'Control details about what and how your site logs access statistics.',
      ),
      'identifier' => 'management_statistics:admin/config/system/statistics',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -15,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_status-report:admin/reports/status.
  $menu_links['management_status-report:admin/reports/status'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/status',
    'router_path' => 'admin/reports/status',
    'link_title' => 'Status report',
    'options' => array(
      'attributes' => array(
        'title' => 'Get a status report about your site\'s operation and any detected problems.',
      ),
      'identifier' => 'management_status-report:admin/reports/status',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -60,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_structure:admin/structure.
  $menu_links['management_structure:admin/structure'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure',
    'router_path' => 'admin/structure',
    'link_title' => 'Structure',
    'options' => array(
      'attributes' => array(
        'title' => 'Administer blocks, content types, menus, etc.',
      ),
      'identifier' => 'management_structure:admin/structure',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -8,
    'customized' => 0,
    'parent_identifier' => 'management_administration:admin',
  );
  // Exported menu link: management_superfish:admin/config/user-interface/superfish.
  $menu_links['management_superfish:admin/config/user-interface/superfish'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/user-interface/superfish',
    'router_path' => 'admin/config/user-interface/superfish',
    'link_title' => 'Superfish',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure Superfish Menus',
      ),
      'identifier' => 'management_superfish:admin/config/user-interface/superfish',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_user-interface:admin/config/user-interface',
  );
  // Exported menu link: management_system:admin/config/system.
  $menu_links['management_system:admin/config/system'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system',
    'router_path' => 'admin/config/system',
    'link_title' => 'System',
    'options' => array(
      'attributes' => array(
        'title' => 'General system related configuration.',
      ),
      'identifier' => 'management_system:admin/config/system',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -20,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_taxonomy:admin/structure/taxonomy.
  $menu_links['management_taxonomy:admin/structure/taxonomy'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/taxonomy',
    'router_path' => 'admin/structure/taxonomy',
    'link_title' => 'Taxonomy',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage tagging, categorization, and classification of your content.',
      ),
      'identifier' => 'management_taxonomy:admin/structure/taxonomy',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_text-formats:admin/config/content/formats.
  $menu_links['management_text-formats:admin/config/content/formats'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/content/formats',
    'router_path' => 'admin/config/content/formats',
    'link_title' => 'Text formats',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure how content input by users is filtered, including allowed HTML tags. Also allows enabling of module-provided filters.',
      ),
      'identifier' => 'management_text-formats:admin/config/content/formats',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_content-authoring:admin/config/content',
  );
  // Exported menu link: management_top-access-denied-errors:admin/reports/access-denied.
  $menu_links['management_top-access-denied-errors:admin/reports/access-denied'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/access-denied',
    'router_path' => 'admin/reports/access-denied',
    'link_title' => 'Top \'access denied\' errors',
    'options' => array(
      'attributes' => array(
        'title' => 'View \'access denied\' errors (403s).',
      ),
      'identifier' => 'management_top-access-denied-errors:admin/reports/access-denied',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_top-page-not-found-errors:admin/reports/page-not-found.
  $menu_links['management_top-page-not-found-errors:admin/reports/page-not-found'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/page-not-found',
    'router_path' => 'admin/reports/page-not-found',
    'link_title' => 'Top \'page not found\' errors',
    'options' => array(
      'attributes' => array(
        'title' => 'View \'page not found\' errors (404s).',
      ),
      'identifier' => 'management_top-page-not-found-errors:admin/reports/page-not-found',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_top-pages:admin/reports/pages.
  $menu_links['management_top-pages:admin/reports/pages'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/pages',
    'router_path' => 'admin/reports/pages',
    'link_title' => 'Top pages',
    'options' => array(
      'attributes' => array(
        'title' => 'View pages that have been hit frequently.',
      ),
      'identifier' => 'management_top-pages:admin/reports/pages',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_top-referrers:admin/reports/referrers.
  $menu_links['management_top-referrers:admin/reports/referrers'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/referrers',
    'router_path' => 'admin/reports/referrers',
    'link_title' => 'Top referrers',
    'options' => array(
      'attributes' => array(
        'title' => 'View top referrers.',
      ),
      'identifier' => 'management_top-referrers:admin/reports/referrers',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_top-visitors:admin/reports/visitors.
  $menu_links['management_top-visitors:admin/reports/visitors'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/visitors',
    'router_path' => 'admin/reports/visitors',
    'link_title' => 'Top visitors',
    'options' => array(
      'attributes' => array(
        'title' => 'View visitors that hit many pages.',
      ),
      'identifier' => 'management_top-visitors:admin/reports/visitors',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 2,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_universally-unique-identifiers:admin/config/system/uuid.
  $menu_links['management_universally-unique-identifiers:admin/config/system/uuid'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/system/uuid',
    'router_path' => 'admin/config/system/uuid',
    'link_title' => 'Universally unique identifiers',
    'options' => array(
      'attributes' => array(
        'title' => 'Configure universally unique identifiers.',
      ),
      'identifier' => 'management_universally-unique-identifiers:admin/config/system/uuid',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_system:admin/config/system',
  );
  // Exported menu link: management_url-aliases:admin/config/search/path.
  $menu_links['management_url-aliases:admin/config/search/path'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/search/path',
    'router_path' => 'admin/config/search/path',
    'link_title' => 'URL aliases',
    'options' => array(
      'attributes' => array(
        'title' => 'Change your site\'s URL paths by aliasing them.',
      ),
      'identifier' => 'management_url-aliases:admin/config/search/path',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -5,
    'customized' => 0,
    'parent_identifier' => 'management_search-and-metadata:admin/config/search',
  );
  // Exported menu link: management_user-interface:admin/config/user-interface.
  $menu_links['management_user-interface:admin/config/user-interface'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/user-interface',
    'router_path' => 'admin/config/user-interface',
    'link_title' => 'User interface',
    'options' => array(
      'attributes' => array(
        'title' => 'Tools that enhance the user interface.',
      ),
      'identifier' => 'management_user-interface:admin/config/user-interface',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => -15,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_user-menu:admin/structure/menu/manage/user-menu.
  $menu_links['management_user-menu:admin/structure/menu/manage/user-menu'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/menu/manage/user-menu',
    'router_path' => 'admin/structure/menu/manage/%',
    'link_title' => 'User menu',
    'options' => array(
      'identifier' => 'management_user-menu:admin/structure/menu/manage/user-menu',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_menus:admin/structure/menu',
  );
  // Exported menu link: management_views-plugins:admin/reports/views-plugins.
  $menu_links['management_views-plugins:admin/reports/views-plugins'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/reports/views-plugins',
    'router_path' => 'admin/reports/views-plugins',
    'link_title' => 'Views plugins',
    'options' => array(
      'attributes' => array(
        'title' => 'Overview of plugins used in all views.',
      ),
      'identifier' => 'management_views-plugins:admin/reports/views-plugins',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_reports:admin/reports',
  );
  // Exported menu link: management_views:admin/structure/views.
  $menu_links['management_views:admin/structure/views'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/structure/views',
    'router_path' => 'admin/structure/views',
    'link_title' => 'Views',
    'options' => array(
      'attributes' => array(
        'title' => 'Manage customized lists of content.',
      ),
      'identifier' => 'management_views:admin/structure/views',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_structure:admin/structure',
  );
  // Exported menu link: management_web-services:admin/config/services.
  $menu_links['management_web-services:admin/config/services'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/services',
    'router_path' => 'admin/config/services',
    'link_title' => 'Web services',
    'options' => array(
      'attributes' => array(
        'title' => 'Tools related to web services.',
      ),
      'identifier' => 'management_web-services:admin/config/services',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: management_workflow:admin/config/workflow.
  $menu_links['management_workflow:admin/config/workflow'] = array(
    'menu_name' => 'management',
    'link_path' => 'admin/config/workflow',
    'router_path' => 'admin/config/workflow',
    'link_title' => 'Workflow',
    'options' => array(
      'attributes' => array(
        'title' => 'Content workflow, editorial workflow tools.',
      ),
      'identifier' => 'management_workflow:admin/config/workflow',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 5,
    'customized' => 0,
    'parent_identifier' => 'management_configuration:admin/config',
  );
  // Exported menu link: menu-about_about:node/261.
  $menu_links['menu-about_about:node/261'] = array(
    'menu_name' => 'menu-about',
    'link_path' => 'node/261',
    'router_path' => 'node/%',
    'link_title' => 'About',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about_about:node/261',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-about_introduction:node/264.
  $menu_links['menu-about_introduction:node/264'] = array(
    'menu_name' => 'menu-about',
    'link_path' => 'node/264',
    'router_path' => 'node/%',
    'link_title' => 'Introduction',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about_introduction:node/264',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: menu-about_project-staff:node/1672.
  $menu_links['menu-about_project-staff:node/1672'] = array(
    'menu_name' => 'menu-about',
    'link_path' => 'node/1672',
    'router_path' => 'node/%',
    'link_title' => 'Project Staff',
    'options' => array(
      'attributes' => array(
        'title' => '',
      ),
      'identifier' => 'menu-about_project-staff:node/1672',
    ),
    'module' => 'menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 1,
  );
  // Exported menu link: navigation_add-content:node/add.
  $menu_links['navigation_add-content:node/add'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add',
    'router_path' => 'node/add',
    'link_title' => 'Add content',
    'options' => array(
      'identifier' => 'navigation_add-content:node/add',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: navigation_add-file:file/add.
  $menu_links['navigation_add-file:file/add'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'file/add',
    'router_path' => 'file/add',
    'link_title' => 'Add file',
    'options' => array(
      'identifier' => 'navigation_add-file:file/add',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: navigation_article:node/add/article.
  $menu_links['navigation_article:node/add/article'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/article',
    'router_path' => 'node/add/article',
    'link_title' => 'Article',
    'options' => array(
      'attributes' => array(
        'title' => 'Use <em>articles</em> for time-sensitive content like news, press releases or blog posts.',
      ),
      'identifier' => 'navigation_article:node/add/article',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'navigation_add-content:node/add',
  );
  // Exported menu link: navigation_basic-page:node/add/page.
  $menu_links['navigation_basic-page:node/add/page'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/page',
    'router_path' => 'node/add/page',
    'link_title' => 'Basic page',
    'options' => array(
      'attributes' => array(
        'title' => 'Use <em>basic pages</em> for your static content, such as an \'About us\' page.',
      ),
      'identifier' => 'navigation_basic-page:node/add/page',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'navigation_add-content:node/add',
  );
  // Exported menu link: navigation_book:node/add/book-info.
  $menu_links['navigation_book:node/add/book-info'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/book-info',
    'router_path' => 'node/add/book-info',
    'link_title' => 'Book',
    'options' => array(
      'attributes' => array(
        'title' => 'Information related to a book',
      ),
      'identifier' => 'navigation_book:node/add/book-info',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'navigation_add-content:node/add',
  );
  // Exported menu link: navigation_compose-tips:filter/tips.
  $menu_links['navigation_compose-tips:filter/tips'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'filter/tips',
    'router_path' => 'filter/tips',
    'link_title' => 'Compose tips',
    'options' => array(
      'identifier' => 'navigation_compose-tips:filter/tips',
    ),
    'module' => 'system',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: navigation_node-export-import:node/add/node_export.
  $menu_links['navigation_node-export-import:node/add/node_export'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/node_export',
    'router_path' => 'node/add/node_export',
    'link_title' => 'Node export: import',
    'options' => array(
      'attributes' => array(
        'title' => 'Import content using <em>Node export</em>.',
      ),
      'identifier' => 'navigation_node-export-import:node/add/node_export',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'navigation_add-content:node/add',
  );
  // Exported menu link: navigation_page-info:node/add/page-info.
  $menu_links['navigation_page-info:node/add/page-info'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/page-info',
    'router_path' => 'node/add/page-info',
    'link_title' => 'Page Info',
    'options' => array(
      'attributes' => array(
        'title' => 'import from old website (page.txt)',
      ),
      'identifier' => 'navigation_page-info:node/add/page-info',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'navigation_add-content:node/add',
  );
  // Exported menu link: navigation_panel:node/add/panel.
  $menu_links['navigation_panel:node/add/panel'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'node/add/panel',
    'router_path' => 'node/add/panel',
    'link_title' => 'Panel',
    'options' => array(
      'attributes' => array(
        'title' => 'A panel layout broken up into rows and columns.',
      ),
      'identifier' => 'navigation_panel:node/add/panel',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
    'parent_identifier' => 'navigation_add-content:node/add',
  );
  // Exported menu link: navigation_popular-content:popular.
  $menu_links['navigation_popular-content:popular'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'popular',
    'router_path' => 'popular',
    'link_title' => 'Popular content',
    'options' => array(
      'identifier' => 'navigation_popular-content:popular',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: navigation_recent-content:tracker.
  $menu_links['navigation_recent-content:tracker'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'tracker',
    'router_path' => 'tracker',
    'link_title' => 'Recent content',
    'options' => array(
      'identifier' => 'navigation_recent-content:tracker',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 1,
    'customized' => 0,
  );
  // Exported menu link: navigation_search:search.
  $menu_links['navigation_search:search'] = array(
    'menu_name' => 'navigation',
    'link_path' => 'search',
    'router_path' => 'search',
    'link_title' => 'Search',
    'options' => array(
      'identifier' => 'navigation_search:search',
    ),
    'module' => 'system',
    'hidden' => 1,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 0,
    'customized' => 0,
  );
  // Exported menu link: user-menu_log-out:user/logout.
  $menu_links['user-menu_log-out:user/logout'] = array(
    'menu_name' => 'user-menu',
    'link_path' => 'user/logout',
    'router_path' => 'user/logout',
    'link_title' => 'Log out',
    'options' => array(
      'identifier' => 'user-menu_log-out:user/logout',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => 10,
    'customized' => 0,
  );
  // Exported menu link: user-menu_user-account:user.
  $menu_links['user-menu_user-account:user'] = array(
    'menu_name' => 'user-menu',
    'link_path' => 'user',
    'router_path' => 'user',
    'link_title' => 'User account',
    'options' => array(
      'alter' => TRUE,
      'identifier' => 'user-menu_user-account:user',
    ),
    'module' => 'system',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 0,
    'weight' => -10,
    'customized' => 0,
  );

  // Translatables
  // Included for use with string extractors like potx.
  t('1801-1860');
  t('1861-1890');
  t('1891-1900');
  t('1901-1950');
  t('1951-1960');
  t('1961-1970');
  t('1971-1980');
  t('1981-1990');
  t('1991-2000');
  t('19th Century');
  t('2001-');
  t('20th Century');
  t('21st Century');
  t('A College Book of American Literature, Vol. 1 (1939)');
  t('A College Book of American Literature, Vol. 2 (1940)');
  t('A History of American Literature (1896)');
  t('A History of American Literature, 1607-1765, Vol. I (1878)');
  t('A History of American Literature, 1607-1765, Vol. II (1878)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. I (1887, 1892)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. II (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. III (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. IV (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. IX (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. V (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. VI (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. VII (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. VIII (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. X (1891)');
  t('A Library of American Literature from the Earliest Settlement to the Present Time, Vol. XI (1891)');
  t('A Treasury of American Literature, Vol. 1 (1955)');
  t('A Treasury of American Literature, Vol. 2 (1955)');
  t('About');
  t('About Menu');
  t('Account settings');
  t('Actions');
  t('Add content');
  t('Add file');
  t('Administration');
  t('Administration menu');
  t('All');
  t('America in Literature, Vol. 1 (1978)');
  t('America in Literature, Vol. 2 (1978)');
  t('American Heritage, Vol. 1 (1955)');
  t('American Heritage, Vol. 2 (1955)');
  t('American Life in Literature, Vol. 1 (1949 Revision)');
  t('American Literary Scholarship');
  t('American Literary Scholarship: An Annual 1963');
  t('American Literary Scholarship: An Annual 1964');
  t('American Literary Scholarship: An Annual 1965');
  t('American Literary Scholarship: An Annual 1966');
  t('American Literature (1983)');
  t('American Literature Extra Essays');
  t('American Literature, 1607-1765 (1886, 1888)');
  t('American Literature, Vol. 1 (1970)');
  t('American Literature, Vol. 2 (1970)');
  t('American Literature, Vol. I (2004)');
  t('American Literature, Vol. II (2004)');
  t('American Literature:  A Prentice Hall Anthology, Vol. 1 (1991)');
  t('American Literature:  A Prentice Hall Anthology, Vol.2 (1991)');
  t('American Literature:  The State of the Art');
  t('American Literature: The Makers and the Making, Vol. 1 (1973)');
  t('American Literature: The Makers and the Making, Vol. 2 (1973)');
  t('American Literature: Tradition & Innovation, Vol. 1 (1969)');
  t('American Literature: Tradition & Innovation, Vol. 2 (1969)');
  t('American Literature: Tradition & Innovation, Vol. 3 (1969)');
  t('American Poetry and Prose (1934)');
  t('American Women Writers to 1800 (1996)');
  t('Anthologies & Histories');
  t('Anthology of American Literature Teacher\'s Edition, Vol. II (2004)');
  t('Anthology of American Literature, Vol. 1 (1974)');
  t('Anthology of American Literature, Vol. 1 (2000)');
  t('Anthology of American Literature, Vol. 1 (2004)');
  t('Appearance');
  t('Article');
  t('Automatic label');
  t('Available updates');
  t('Back To Top');
  t('Backup and Migrate');
  t('Basic page');
  t('Blocks');
  t('Book');
  t('Bulk Exporter');
  t('CKEditor');
  t('Canons by Consensus');
  t('Century Readings for a Course in American Literature (1919)');
  t('Clean URLs');
  t('Colonial American Literature (1976)');
  t('Colonial American Writing (1950)');
  t('Colonial American Writing (1969)');
  t('Colonial and Federal to 1800 (1962)');
  t('Colonial and Federalist American Writing (1966)');
  t('Columbia Literary History of the United States (1988)');
  t('Comments');
  t('Compose tips');
  t('Configuration');
  t('Content');
  t('Content authoring');
  t('Content types');
  t('Cron');
  t('Current search blocks');
  t('Cyclopaedia of American Literature, Vol. I (1855)');
  t('Cyclopaedia of American Literature, Vol. II (1855)');
  t('Dashboard');
  t('Data export import');
  t('Date API');
  t('Date Tools');
  t('Date and time');
  t('Development');
  t('Early American Drama (1997)');
  t('Early American Poetry (1978)');
  t('Early American Writing (1994)');
  t('Early American Writings (2002)');
  t('Eight American Writers: An Anthology of American Literature (1963)');
  t('English Literatures of America, 1500-1800 (1997)');
  t('Features');
  t('Field list');
  t('File settings');
  t('File system');
  t('File types');
  t('Harper American Literature, Vol. 1 (1987)');
  t('Harper American Literature, Vol. 1 (1993)');
  t('Harper American Literature, Vol. 2 (1987)');
  t('Harper American Literature, Vol. 2 (1993)');
  t('Help');
  t('Home');
  t('IMCE');
  t('IP address blocking');
  t('Image styles');
  t('Image toolkit');
  t('Introduction');
  t('Lectures on American Literature (1829)');
  t('Literary History of the United States (1946, 1948)');
  t('Log out');
  t('Logging and errors');
  t('Main Currents in American Thought (1927)');
  t('Main menu');
  t('Maintenance mode');
  t('Major American Writers (1952)');
  t('Major Writers of America, Vol. 1 (1962)');
  t('Major Writers of America, Vol. 2 (1962)');
  t('Major Writers of Early American Literature, Critical Essays (1972)');
  t('Management');
  t('Masters of American Literature (1959)');
  t('Masters of American Literature, Vol. 1 (1949)');
  t('Masters of American Literature, Vol. 2 (1949)');
  t('Media');
  t('Media Browser Plus Settings');
  t('Media browser settings');
  t('Menus');
  t('Mini panels');
  t('Module filter');
  t('Modules');
  t('Navigation');
  t('Node export');
  t('Node export: import');
  t('O Brave New World: American Literature 1600-1840 (1968)');
  t('Other Resources');
  t('Page Info');
  t('Pages');
  t('Panel');
  t('Panels');
  t('People');
  t('Performance');
  t('Popular content');
  t('Project Staff');
  t('RSS publishing');
  t('Recent content');
  t('Recent hits');
  t('Recent log messages');
  t('Regional and language');
  t('Regional settings');
  t('Reports');
  t('Search');
  t('Search API');
  t('Search and metadata');
  t('Shortcuts');
  t('Site information');
  t('Statistics');
  t('Status report');
  t('Structure');
  t('Superfish');
  t('System');
  t('Taxonomy');
  t('Text formats');
  t('The American Tradition in Literature (1994)');
  t('The American Tradition in Literature, Vol. 1 (1956)');
  t('The American Tradition in Literature, Vol. 2 (1956)');
  t('The Cambridge History of American Literature, 1590-1820, Vol. 1 (1994)');
  t('The Cambridge History of American Literature, 1590-1820, Vol. 2 (1994)');
  t('The Cambridge History of American Literature, 1590-1820, Vol. 7 (1994)');
  t('The Cambridge History of American Literature, 1590-1820, Vol. 8 (1994)');
  t('The Chief American Prose Writers (1916)');
  t('The Cycle of American Literature (1955)');
  t('The First Century of American Literature, 1770-1870 (1935, 1966)');
  t('The Growth of American Literature, Vol. 1 (1956)');
  t('The Growth of American Literature, Vol. 2 (1956)');
  t('The Harper Single Volume American Literature (1999)');
  t('The Heath Anthology of American Literature (2004)');
  t('The Heath Anthology of American Literature, Vol. 1 (1990)');
  t('The Heath Anthology of American Literature, Vol. 1 (1998)');
  t('The Heath Anthology of American Literature, Vol. 1 (2002)');
  t('The Heath Anthology of American Literature, Vol. 2 (1990)');
  t('The Heath Anthology of American Literature, Vol. 2 (1998)');
  t('The Heath Anthology of American Literature, Vol. 2 (2002)');
  t('The Heath Anthology of American Literature, Vol. A (2006)');
  t('The Heath Anthology of American Literature, Vol. B (2006)');
  t('The Heath Anthology of American Literature, Vol. C (2006)');
  t('The Heath Anthology of American Literature, Vol. D (2006)');
  t('The Heath Anthology of American Literature, Vol. E (2006)');
  t('The Heritage of American Literature, Vol. 1 (1951)');
  t('The Heritage of American Literature, Vol. 2 (1951)');
  t('The Literature of America: Colonial Period (1970)');
  t('The Literature of the United States, Vol. 1 (1953)');
  t('The Literature of the United States, Vol. 2 (1953)');
  t('The Literatures of Colonial America (2001)');
  t('The Meridian Anthology of Early American Women Writers (1991)');
  t('The New Anthology of American Poetry, Vol. 1 (2003)');
  t('The Norton Anthology of American Literature, Vol. 1 (1979)');
  t('The Norton Anthology of American Literature, Vol. 1 (1998)');
  t('The Norton Anthology of American Literature, Vol. 2 (1979)');
  t('The Norton Anthology of American Literature, Vol. 2 (1998)');
  t('Three Centuries of American Poetry 1620-1923 (1999)');
  t('Top \'access denied\' errors');
  t('Top \'page not found\' errors');
  t('Top pages');
  t('Top referrers');
  t('Top visitors');
  t('Twelve American Writers (1962)');
  t('URL aliases');
  t('Universally unique identifiers');
  t('User account');
  t('User interface');
  t('User menu');
  t('Views');
  t('Views plugins');
  t('Web services');
  t('Who are the Major American Writers? (1972)');
  t('Workflow');
  t('jQuery Update');

  return $menu_links;
}
